def get_auto_names():
    data = [
    "Abarth",
    "Aixam",
    "AC Cars",
    "Acura",
    "Alfa Romeo",
    "Alpina",
    "Alpine",
    "Ariel",
    "Aston Martin",
    "Audi",
    "BAC",
    "Bentley",
    "BMW",
    "Brabus",
    "Bugatti",
    "Buick",
    "BYD",
    "Cadillac",
    "Callaway",
    "Canoo",
    "Caterham",
    "Changan",
    "Chery",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Citroën",
    "Cupra",
    "Dacia",
    "Daewoo",
    "Daihatsu",
    "Datsun",
    "DeLorean",
    "Dodge",
    "DS Automobiles",
    "Duesenberg",
    "Dymaxion",
    "Eagle",
    "Faraday Future",
    "Ferrari",
    "Fiat",
    "Fisker",
    "Ford",
    "Foton",
    "GAZ",
    "Geely",
    "Genesis",
    "GMC",
    "Gordon Murray",
    "Great Wall",
    "GTA Motor",
    "Gumpert",
    "Hennessey",
    "Holden",
    "Honda",
    "Hudson",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Innocenti",
    "Isuzu",
    "IVECO",
    "JAC Motors",
    "Jaguar",
    "Jeep",
    "Jensen",
    "Karma",
    "Kia",
    "Koenigsegg",
    "KTM",
    "Lada",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "LeEco",
    "Lexus",
    "Li Auto",
    "Lincoln",
    "Lotus",
    "Lucid",
    "Mahindra",
    "Maserati",
    "Maybach",
    "Mazda",
    "McLaren",
    "Mercedes",
    "Mercedes-Benz",
    "Mercury",
    "MG",
    "Micro",
    "Mini",
    "Mitsubishi",
    "Mitsuoka",
    "Morgan",
    "Morris",
    "Nikola",
    "Nio",
    "Nissan",
    "Noble",
    "Oldsmobile",
    "Opel",
    "Pagani",
    "Panoz",
    "Perodua",
    "Peugeot",
    "Pininfarina",
    "Plymouth",
    "Polestar",
    "Pontiac",
    "Porsche",
    "Proton",
    "Qoros",
    "RAM",
    "Renault",
    "Ravon",
    "Rimac",
    "Rivian",
    "Roewe",
    "Rolls-Royce",
    "Rover",
    "Saab",
    "SAIC Motor",
    "Saleen",
    "Saturn",
    "Scania",
    "Scion",
    "SEAT",
    "Shelby",
    "Skoda",
    "Smart",
    "SsangYong",
    "SSC",
    "Standard",
    "Studebaker",
    "Subaru",
    "Suzuki",
    "Talbot",
    "Tata",
    "Tatra",
    "Tesla",
    "Think",
    "Toyota",
    "Trabant",
    "Triumph",
    "TVR",
    "Ultima",
    "Vauxhall",
    "Volkswagen",
    "Vw",
    "Volvo",
    "W Motors",
    "Wanderer",
    "Wuling",
    "ZAZ",
    "Zenvo",
    "ZX Auto"
]

    return data
